export const theme = {
  fontFamily:
    'Inter, "Segoe UI", ui-sans-serif, system-ui, -apple-system, sans-serif',
  colors: {
    bg: "#F5F5F7",
    surface: "#FFFFFF",
    text: "#1D1D1F",
    muted: "#6E6E73",
    border: "#E5E5EA",
    accent: "#007AFF",
    good: "#34C759",
    warn: "#FF9500",
    danger: "#FF3B30",
    overlay: "rgba(0, 0, 0, 0.45)",
  },
  radius: {
    sm: "10px",
    md: "16px",
    lg: "24px",
    pill: "999px",
  },
  shadow: "0 12px 40px rgba(0, 0, 0, 0.08)",
};

export const styles = {
  app: {
    minHeight: "100vh",
    background: theme.colors.bg,
    color: theme.colors.text,
    fontFamily: theme.fontFamily,
    padding: "24px",
    boxSizing: "border-box",
  },
  shell: {
    maxWidth: "440px",
    margin: "0 auto",
    background: theme.colors.surface,
    borderRadius: theme.radius.lg,
    border: `1px solid ${theme.colors.border}`,
    boxShadow: theme.shadow,
    padding: "24px",
  },
  header: {
    marginBottom: "20px",
  },
  title: {
    margin: 0,
    fontSize: "28px",
    fontWeight: 700,
    letterSpacing: "-0.03em",
  },
  subtitle: {
    margin: "6px 0 0",
    color: theme.colors.muted,
    fontSize: "14px",
    lineHeight: 1.5,
  },
  statusCard: {
    borderRadius: theme.radius.md,
    padding: "16px",
    background: "#F2F2F7",
    marginBottom: "16px",
  },
  statusLabel: {
    margin: 0,
    fontSize: "12px",
    color: theme.colors.muted,
    fontWeight: 600,
  },
  statusValue: {
    margin: "8px 0 0",
    fontSize: "18px",
    fontWeight: 600,
    whiteSpace: "pre-line",
  },
  videoWrap: {
    borderRadius: theme.radius.md,
    overflow: "hidden",
    background: "#111",
    marginBottom: "16px",
  },
  video: {
    width: "100%",
    aspectRatio: "4 / 3",
    objectFit: "cover",
    transform: "scaleX(-1)",
    display: "block",
  },
  videoHidden: {
    width: "1px",
    height: "1px",
    position: "absolute",
    opacity: 0,
    pointerEvents: "none",
  },
  buttonRow: {
    display: "grid",
    gap: "10px",
  },
  button: {
    border: "none",
    borderRadius: theme.radius.sm,
    padding: "12px 16px",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    background: theme.colors.text,
    color: "#fff",
  },
  buttonSecondary: {
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.sm,
    padding: "12px 16px",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    background: theme.colors.surface,
    color: theme.colors.text,
  },
  buttonDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  privacy: {
    marginTop: "16px",
    fontSize: "12px",
    lineHeight: 1.55,
    color: theme.colors.muted,
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "12px",
    fontSize: "14px",
    color: theme.colors.muted,
  },
  testSection: {
    marginTop: "20px",
    paddingTop: "16px",
    borderTop: `1px solid ${theme.colors.border}`,
  },
  testSectionLabel: {
    margin: "0 0 8px",
    fontSize: "12px",
    fontWeight: 600,
    color: theme.colors.muted,
  },
  testButtonRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
  },
  testSectionHint: {
    margin: "8px 0 0",
    fontSize: "11px",
    lineHeight: 1.5,
    color: theme.colors.muted,
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: theme.colors.overlay,
    display: "grid",
    placeItems: "center",
    zIndex: 10000,
    padding: "24px",
  },
  centerCard: {
    width: "min(440px, 100%)",
    background: theme.colors.surface,
    borderRadius: theme.radius.lg,
    padding: "28px",
    boxShadow: "0 24px 80px rgba(0,0,0,0.2)",
    textAlign: "left",
  },
  centerTitle: {
    margin: "0 0 8px",
    fontSize: "22px",
    fontWeight: 700,
    textAlign: "center",
  },
  centerMessage: {
    margin: "0 0 20px",
    color: theme.colors.muted,
    whiteSpace: "pre-line",
    lineHeight: 1.6,
    textAlign: "center",
  },
  animBox: {
    width: "100%",
    height: "180px",
    borderRadius: theme.radius.md,
    background: "linear-gradient(180deg, #F8FAFC 0%, #EEF2FF 100%)",
    marginBottom: "20px",
    display: "grid",
    placeItems: "center",
    overflow: "hidden",
  },
  actionRow: {
    display: "grid",
    gap: "8px",
  },
};
